apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dpvc-host
  namespace: lab3
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem