apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-mysql-pvc
  namespace: lab3
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage