apiVersion: v1
kind: Service
metadata:
  name: applb
  namespace: lab3
  labels:
    name: lb-svc
    app: employees
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer      
