apiVersion: v1
kind: Service
metadata:
  name: applb
  namespace: lab3
  labels:
	app: lbsvc	
spec:
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
