apiVersion: v1
kind: PersistentVolumeClaim
metadata:
	name:
	namespace:
	annotations
	  volume.beta.kubernetes.io/storage-class: gp2
spec:
  resources:
    requests:
	storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: 