apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-host
  namespace: lab3
  labels:
    app: mysql
spec:
  resources:
    requests:
	  storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: localstorage
