apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:
  namespace: lab3
  labels:
    app: mysql
spec:
  resources:
    requests:
	storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: 
