apiVersion: v1
kind: PersistentVolume
metadata:
  name:
  namespace:
  labels:
    app: mysql
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/data
  storageClassName: